# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uZZ_Ppk5PfUSXP1xkfzXXiwd-KAV4y1T
"""

from datetime import datetime
import random as rand
from datetime import datetime
import os 
from tqdm import tqdm # progress bar
import sys
from time import time 
import argparse


delimiter = ', ' 
rand.seed(42)
dash = '-'*80

def createFolderInDrive(folder_name, date = None, exercise_number = None ):
  """
  folder_name = string format 'DescriptiveName'
  date = default None, either custom string 'YYYYMMDD' either datetime.today().strftime('%Y%m%d') 
  exercise_number = default None
  """

  root= "/content/drive/My Drive/%s" %(folder_name)
  

  #os.mkdir ("/content/drive/My Drive/02582-ComputationalDataAnalysis")
  #print (dash)
  if (date is None) & (exercise_number is None):
     
    print ("No date specified, no exercise number specified")
    #print (root)

    while os.path.exists(root) == False:
      print ('%s folder is missing!'%(folder_name))
      os.mkdir (root)
      print ('Folder created in:')
      print (root)
      print (dash)
    if os.path.exists(root) == True:
      print ('%s exist'%(folder_name))
  
  if (date is not None) & (exercise_number is None): 
    savepath = root+'/'+date

    print ("No exercise number specified")
    #print (savepath)

    while os.path.exists(savepath) == False:
      print ('%s folder is missing!'%(savepath))
      os.mkdir (savepath)
      print ('Folder created in:')
      print (savepath)
      print (dash)
    if os.path.exists(savepath) == True:
      print ('%s exist'%(savepath))

  if (date is None) & (exercise_number is not None): 
    exercise_root = root+'/'+exercise_number

    print ("No date specified")
    #print (exercise_root)

    while os.path.exists(exercise_root) == False:
      print ('%s folder is missing!'%(exercise_root))
      os.mkdir (exercise_root)
      print ('Folder created in:')
      print (exercise_root)
      print (dash)
    if os.path.exists(exercise_root) == True:
      print ('%s exist'%(exercise_root))

  if (date is not None) & (exercise_number is not None): 
    
    full_exercise_root = root+'/'+date+'/'+exercise_number
    #print (full_exercise_root)

    while os.path.exists(full_exercise_root) == False:
      print ('%s folder is missing!'%(full_exercise_root))
      os.mkdir (full_exercise_root)
      print ('Folder created in:')
      print (full_exercise_root)
      print (dash)
    if os.path.exists(full_exercise_root) == True:
      print ('%s exist'%(full_exercise_root))

  return

